name: Rust Test

on: [push, pull_request]

jobs: 
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - run: cargo check
    
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - run: cargo fmt -- --check
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - run: cargo test --all -- --test-threads=1