name: Rust Test

on: [push, pull_request]

jobs: 
  check:
    name: test
    runs-on: ubuntu-latest
    working-directory: ./database
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: check
        run: cargo check
      - name: fmt
        run: cargo fmt -- --check
      - name: test
        run: cargo test --all -- --test-threads=1